### ISSUE TITLE
Loglevels instead of only true/false

### ISSUE THREAD

**Issue by joeherwig** [werbasinnotec/snooper#1]
Great and easy module for forwarding logmessages to a hosted logging-server.
Suggestion: It would be great, if you could change the behaviour so that instead of just switching on and off via environment variable handing over the message levels which have to be sent.

eg. `-e SNOOPER_FORWARD_ACTIVE=fatal,error`

**Comment by mwiesmueller** [comment]
Fixed with 4afe927 - Implementate Loglevels for forward-messages.
